name: Create Requirements
on:
  issues:
    types: [labeled]
jobs:
  create_requirements:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'doc:requirements'
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Requirements Issue
        id: claude
        uses: anthropics/claude-code-action@v1.0.70
        with:
          prompt_file: ".claude/prompts/create-requirements.txt"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          claude_args: "--allowedTools 'Bash(gh issue edit:*)'"
